### ISSUE TITLE
Windows VC2022 - Compiler error code 9009 for postgres_scanner (maybe a template issue?)

### ISSUE THREAD

**Issue by orzom411** [duckdb/extension-template#16]
I started out looking for guidance, not sure how to include postgres_scanner in the full duckdb build on windows 10, 64 bit environment.  My hope is the issues I had might help others navigate through.  I suspect part of the issues I experienced was a cmake conversion glitch, maybe the template, if it isn't please just reject this.

Building labs postgres_scanner found an issue in the the .vcxproj, it is making a call to "sh" in a windows environment, "sh" doesn't exist.  I do not know nearly enough about the cmake process to suggest a fix but I do have a mitigation to offer.

I edited the postgres_scanner_loadable_extension.vcxproj, replacing:
`sh` pgconfigure

Instead I employed the bash environment that comes with git, e.g.:
`"C:\Program` Files\Git\bin\bash.exe" -c "sh pgconfigure"

This worked and I was able to run into the next issue, versions.

I've captured a lot of additional detail but I believe those a lot more knowledgeable about cmake and resulting vcxproj files will understand the mitigation. 

Full path:
C:\duckdb\extension\postgres_scanner\postgres_scanner_loadable_extension.vcxproj`

Hope this helps the next poor soul trying to build out this extension in windows.

**Comment by samansmink** [comment]
Lots of things changed since this issue, so it is probably not relevant anymore. building extensions for windows should be properly handled by the template now, if not please open a new issue!
