### ISSUE TITLE
Create schema in extension transaction not available to TableFunction CreateView

### ISSUE THREAD

**Issue by rupurt** [duckdb/extension-template#27]
Howdy,

I'm trying to create an ODBC extension that maps an attached database to DuckDB schemas and views. I'm following the structure of the Postgres extension which has been super helpful but it uses the default `main` schema in the `memory` catalog. I can get it to work if I start a new transaction for every row of [SQLTables](https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqltables-function?view=sql-server-ver16) but ideally I would like everything to be rolled back if there is a failure. It also works sometimes if I create the schemas in the bind function and the views in the attach function. This makes me think there is some background work or data in a buffer that has not been flushed.

Are there any examples of this you can point me to? Or do you have a recommended approach for this kind of thing?

I have attached a copy of my branch that is causing the issue https://github.com/rupurt/odbc-scanner-duckdb-extension/compare/odbc-attach-schema-not-found#diff-3f910f46660aa2e53cd6309da4fc6ff8fe21edc2321d24271f90932ca708c7b2R274

Cheers :beers:

**Comment by Mytherin** [comment]
You may want to have a look at the revamped [SQLite extension](https://github.com/Mytherin/sqlite_scanner) that doesn't rely on creating views, but instead allows you to `ATTACH` sqlite databases instead (see duckdb/duckdb#6066)
