### ISSUE TITLE
Extension Does not Build for DuckDB v0.8.1

### ISSUE THREAD

**Issue by MarkRoddy** [duckdb/extension-template#28]
When I create an extension repo, and try to build it using DuckDB v0.8.1 (latest release as of this writing), the extension does not get built. I attempt to execute the `quack()` scalar function and it isn't found. Additionally, the extension doesn't exist at `build/release/extension/quack/quack.duckdb_extension`. Though the directory `build/release/extension/quack/` does.

## Steps to reproduce:
1. Create a new repo from this template.
2. Update the DuckDB git submodule to point to the `v0.8.1` tag.
3. run `make`
4. Run `./build/release/duckdb`
5. Run `select quack('Jane') as result;`

## Expected result:
The query result documented in the README:
```sql
D select quack('Jane') as result;
┌───────────────┐
│    result     │
│    varchar    │
├───────────────┤
│ Quack Jane 🐥 │
└───────────────┘
```

## Actual Result:
```sql
D select quack('Jane') as result;
Error: Catalog Error: Scalar Function with name quack does not exist!
Did you mean "acos"?
LINE 1: select quack('Jane') as result;
               ^
D load quack;
Error: IO Error: Extension "/home/mark/.duckdb/extensions/v0.8.1/linux_amd64/quack.duckdb_extension" not found.

Candidate extensions: "icu"
```

edit: formatting

**Comment by MarkRoddy** [comment]
I was able to resolve this issue by reverting changes to the Makefile I found [here](https://github.com/duckdb/extension-template/commit/0281b9014a07b31aa6efc01e2dc9c84224bcd0a6#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L26). When using the old values for `EXTENSION_FLAGS`, the extension was built as expected.

**Comment by samansmink** [comment]
DuckDB v0.9.0 was release and the template now targets that. I'll close this issue!
