### ISSUE TITLE
some questions about table function extension

### ISSUE THREAD

**Issue by PinappleUnderTheSea** [duckdb/extension-template#75]
Hihi!
 I am trying to implement a table function extension which is used to read remote data in a server. These data readers are devided and i want to concurrently read them. I studied codes in parquet extension but I could not find where duckdb enables multi threads. Can you give me some advise about how to run in parallel? I have set global state and local state but they did not work. GDB told me there were 15 threads working but the performance shows that they works sequentially. Thanks a lot

Appreciate it!

**Comment by samansmink** [comment]
Hey @PinappleUnderTheSea

We currently don't have a centralized documentation on this. But I can give you some pointers.

In general, will need to implement the `init_global` and `init_local` functions of the [TableFunction API](https://github.com/duckdb/duckdb/blob/794fe1efb96e8fe15d1805f197d5df9b06a4f82f/src/include/duckdb/function/table_function.hpp#L224), then make sure you define the `MaxThreads()` function on your GlobalState like [here](https://github.com/duckdb/duckdb/blob/794fe1efb96e8fe15d1805f197d5df9b06a4f82f/extension/parquet/parquet_extension.cpp#L136).

Also, maybe [this](https://www.youtube.com/watch?v=MA0OsvYFGrc) video can be helpful in better understanding the multithreading model

Finally, here are some more examples of parallel tablefunctions
- the [seq_scan](https://github.com/duckdb/duckdb/blob/794fe1efb96e8fe15d1805f197d5df9b06a4f82f/src/function/table/table_scan.cpp#L401) internal table function 
- the [arrow_scan](https://github.com/duckdb/duckdb/blob/794fe1efb96e8fe15d1805f197d5df9b06a4f82f/src/function/table/arrow.cpp#L417) function 

hope that helps! btw also check out the [discord](https://discord.com/invite/tcvwpjfnZx) for help, there's a dedicated extensions channel
